PrecastFactorySystem/Areas/Admin/Controllers/PrecastController.cs
namespace PrecastFactorySystem.Web.Areas.Admin.Controllers
{
	using Microsoft.AspNetCore.Mvc;

	using PrecastFactorySystem.Core.Contracts;
	using PrecastFactorySystem.Core.Models.Precast;
	using PrecastFactorySystem.Infrastructure.Data.Models;
	using PrecastFactorySystem.Web.Attributes;

	public class PrecastController : AdminBaseController
	{
		private readonly IPrecastService precastService;
		private readonly IBaseServise baseService;

		public PrecastController(IPrecastService _precastService,
						IBaseServise _baseService)
		{
			precastService = _precastService;
			baseService = _baseService;
		}
		public async Task<IActionResult> All([FromQuery] AllPrecastQueryModel model)
		{
			var precasts = await precastService.GetAllPrecastAsync(
				model.SearchTerm,
				model.ProjectId,
				model.PrecastTypeId,
			model.Sorting,
			model.CurrentPage,
				AllPrecastQueryModel.PrecastsPerPage);

			model.Projects = await baseService.GetBaseEntityDataAsync<Project>();
			model.PrecastTypes = await baseService.GetBaseEntityDataAsync<PrecastType>();
			model.Precast = precasts.Precast;
			model.TotalPrecast = precasts.TotalPrecast;

			return View(model);
		}


		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Delete(int id)
		{
			var model = await baseService.GetEntityBaseInfoAsync<Precast>(id);
			return View(model);
		}

		[PrecastExists]
		[HttpPost]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await baseService.DeleteEntityAsync<Precast>(id);
			TempData["Message"] = "You have successfully deleted precast!";
			return RedirectToAction(nameof(All));
		}
	}
}

PrecastFactorySystem/Controllers/OrderController.cs
namespace PrecastFactorySystem.Web.Controllers
{
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Mvc;

	using PrecastFactorySystem.Core.Contracts;
	using PrecastFactorySystem.Core.Exceptions;
	using PrecastFactorySystem.Core.Models;
	using PrecastFactorySystem.Core.Models.Order;
	using PrecastFactorySystem.Infrastructure.Data.Models;
	using PrecastFactorySystem.Web.Attributes;
	
	using static PrecastFactorySystem.Core.Constants.MessageConstants;

	public class OrderController : BaseController
	{
		private readonly IOrderService orderService;
		private readonly IPrecastService precastService;
		private readonly IBaseServise baseService;
		private readonly IExportService exportService;
		private readonly IEmailService emailService;

		public OrderController(IOrderService _orderService,
			IPrecastService _precastService,
			IBaseServise _baseService,
			IExportService _exportService,
			IEmailService _emailService)
		{
			orderService = _orderService;
			precastService = _precastService;
			baseService = _baseService;
			exportService = _exportService;
			emailService = _emailService;
		}

		[HttpGet]
		public async Task<IActionResult> All([FromQuery] AllOrdersQueryModel model)
		{
			var orders = await orderService.GetReinforceOrdersAsync(
				model.SearchTerm,
				model.ProjectId,
				model.DepartmentId,
				model.FromDate,
				model.ToDate,
				model.CurrentPage,
				AllOrdersQueryModel.OrdersPerPage);

			model.Projects = await baseService.GetBaseEntityDataAsync<Project>();
			model.Departments = await baseService.GetBaseEntityDataAsync<Department>();
			model.Orders = orders.Orders;
			model.TotalOrders = orders.TotalOrders;

			return View(model);
		}

		[Authorize(Roles = "Administrator, ReinforceManager")]
		[HttpGet]
		[PrecastExists]
		public async Task<IActionResult> Order(int id)
		{
			try
			{
				OrderPrecastReinforceViewModel model = await orderService.GetOrderPrecastReinforceViewModel(id);
				return View(model);
			}
			catch (OrderActionException oae)
			{
				return View("BaseError", new BaseErrorViewModel()
				{
					Message = oae.Message
				});
			}

		}

		[Authorize(Roles = "Administrator, ReinforceManager")]
		[HttpPost]
		[PrecastExists]
		public async Task<IActionResult> Order(int id, OrderPrecastReinforceViewModel model)
		{
			try
			{
				int maxCountToBeOrdered = await orderService.GetPrecastToReinforceCountAsync(id);

				if (model.OrderedCount > maxCountToBeOrdered)
				{
					ModelState.AddModelError(nameof(model.OrderedCount),
						string.Format(InvalidOrderCountErrorMessage, maxCountToBeOrdered));
				}

				if (!ModelState.IsValid)
				{
					model.Deliverers = await baseService.GetBaseEntityDataAsync<Deliverer>();
					model.Departments = await baseService.GetBaseEntityDataAsync<Department>();
					return View(model);
				}

				var orderModel = await orderService.OrderPrecastAsync(id, model);

				byte[] bytes = exportService.ExportOrderToPdf(orderModel);

				var fileName = $"Order {orderModel.OrderNum} - {orderModel.Precast}  {orderModel.Project}";

				var IsSuccess = await emailService.SendOrderEmailAsync(orderModel.DelivererEmail, fileName, bytes);

				if (IsSuccess)
				{
					await orderService.SaveOrderAsync(orderModel);
					TempData["Message"] = "You have successfully ordered precast!";
				}
				else
				{
					TempData["Message"] = "Something went wrong, and the order was not created!";
				}

				return RedirectToAction("Reinforce", "Precast", new { id });
			}
			catch (OrderActionException oae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = oae.Message
				});
			}



		}


		[Authorize(Roles = "Administrator, ReinforceManager")]
		[HttpGet]
		[OrderExists]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				DeleteOrderViewModel model = await orderService.CheckOrderToDeleteByIdAsync(id);
				return View(model);
			}
			catch (DeleteActionException dae)
			{
				return View("BaseError", new BaseErrorViewModel()
				{
					Message = dae.Message
				});
			}

		}

		[Authorize(Roles = "Administrator, ReinforceManager")]
		[HttpPost]
		[OrderExists]
		public async Task<IActionResult> DeleteConfirmed(int id,string delivererEmail)
		{
			try
			{
				var IsSuccess = await emailService.SendCancelOrderEmailAsync(delivererEmail, $"Order N:  {id}");
				if (IsSuccess)
				{
					TempData["Message"] = "You have successfully deleted order!";
					await orderService.DeleteOrderAsync(id);
				}
				else
				{
					TempData["Message"] = "Something went wrong, and the order was not deleted!";
				}

				return RedirectToAction(nameof(All));
			}
			catch (DeleteActionException dae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = dae.Message
				});
			}
		}

		[Authorize(Roles = "Administrator, ReinforceManager")]
		[HttpGet]
		[PrecastExists]
		public async Task<IActionResult> ForPrecast(int id, [FromQuery] AllPrecastOrdersQueryModel model)
		{
			var orders = await orderService.GetReinforceOrdersByPrecastAsync(
				id,
				model.CurrentPage,
				AllPrecastOrdersQueryModel.OrdersPerPage);

			model.Orders = orders.Orders;
			model.TotalOrders = orders.TotalOrders;

			ViewBag.PrecastId = id;
			return View(model);
		}
	}
}

PrecastFactorySystem/Controllers/PrecastController.cs
namespace PrecastFactorySystem.Web.Controllers
{
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Mvc;

	using PrecastFactorySystem.Core.Contracts;
	using PrecastFactorySystem.Core.Exceptions;
	using PrecastFactorySystem.Core.Models;
	using PrecastFactorySystem.Core.Models.Precast;
	using PrecastFactorySystem.Web.Attributes;

	using PrecastFactorySystem.Infrastructure.Data.Models;

	using static Core.Constants.MessageConstants;

	public class PrecastController : BaseController
	{
		private readonly IPrecastService precastService;
		private readonly IBaseServise baseService;
		private readonly IReinforceService reinforceService;

		public PrecastController(IPrecastService _precastService,
			IBaseServise _baseService,
			IReinforceService _reinforceService)
		{
			precastService = _precastService;
			baseService = _baseService;
			reinforceService = _reinforceService;
		}

		[HttpGet]
		public async Task<IActionResult> All([FromQuery] AllPrecastQueryModel model)
		{
			var precasts = await precastService.GetAllPrecastAsync(
				model.SearchTerm,
				model.ProjectId,
				model.PrecastTypeId,
				model.Sorting,
				model.CurrentPage,
				AllPrecastQueryModel.PrecastsPerPage);

			model.Projects = await baseService.GetBaseEntityDataAsync<Project>();
			model.PrecastTypes = await baseService.GetBaseEntityDataAsync<PrecastType>();
			model.Precast = precasts.Precast;
			model.TotalPrecast = precasts.TotalPrecast;

			return View(model);
		}

		[Authorize(Roles = "Administrator, Manager")]
		[HttpGet]
		public async Task<IActionResult> Add()
		{
			PrecastFormViewModel model = new PrecastFormViewModel()
			{
				Projects = await baseService.GetBaseEntityDataAsync<Project>(),
				Types = await baseService.GetBaseEntityDataAsync<PrecastType>(),
				Concrete = await baseService.GetBaseEntityDataAsync<ConcreteClass>()
			};

			return View(model);
		}

		[Authorize(Roles = "Administrator, Manager")]
		[HttpPost]
		public async Task<IActionResult> Add(PrecastFormViewModel model)
		{
			if (!ModelState.IsValid)
			{
				model.Projects = await baseService.GetBaseEntityDataAsync<Project>();
				model.Types = await baseService.GetBaseEntityDataAsync<PrecastType>();
				model.Concrete = await baseService.GetBaseEntityDataAsync<ConcreteClass>();

				return View(model);
			}

			await precastService.AddPrecastAsync(model);

			TempData["Message"] = "You have successfully added precast!";
			return RedirectToAction(nameof(All));
		}

		[Authorize(Roles = "Administrator, Manager")]
		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			PrecastFormViewModel model = await precastService.GetPrecastByIdAsync(id);
			return View(model);
		}

		[Authorize(Roles = "Administrator, Manager")]
		[PrecastExists]
		[HttpPost]
		public async Task<IActionResult> Edit(PrecastFormViewModel model, int id)
		{
			int reinforced = await precastService.GetReinforcedPrecastCountAsync(id);

			if (model.Count < reinforced)
			{
				ModelState.AddModelError(nameof(model.Count),
					string.Format(InvalidPrecastCountErrorMessage, reinforced));
			}

			if (!ModelState.IsValid)
			{
				model.Projects = await baseService.GetBaseEntityDataAsync<Project>();
				model.Types = await baseService.GetBaseEntityDataAsync<PrecastType>();
				model.Concrete = await baseService.GetBaseEntityDataAsync<ConcreteClass>();

				return View(model);
			}
			await precastService.EditPrecastAsync(id, model);
			TempData["Message"] = "You have successfully edited precast!";
			return RedirectToAction(nameof(All));

		}


		[PrecastExists]
		public async Task<IActionResult> Details(int id)
		{
			PrecastDetailsViewModel model = await precastService.GetPrecastDetailsAsync(id);
			return View(model);
		}

		[Authorize(Roles = "Administrator, Manager")]
		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				PrecastDeleteViewModel model = await precastService.GetPrecastToDeleteByIdAsync(id);
				return View(model);
			}
			catch (DeleteActionException dae)
			{
				return View("BaseError", new BaseErrorViewModel()
				{
					Message = dae.Message
				});
			}

		}

		[Authorize(Roles = "Administrator, Manager")]
		[PrecastExists]
		[HttpPost]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			try
			{
				await precastService.DeletePrecastAsync(id);
				TempData["Message"] = "You have successfully deleted precast!";
				return RedirectToAction(nameof(All));
			}
			catch (DeleteActionException dae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = dae.Message
				});
			}



		}

		[Authorize(Roles = "Administrator, ReinforceManager")]
		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Reinforce(int id, [FromQuery] AllPrecastReinforceQueryModel model)
		{
			PrecastReinforceQueryModel precastReinforce = await precastService.GetPrecastReinforceAsync(
				id,
				model.CurrentPage,
				AllPrecastReinforceQueryModel.ReinforcePerPage);

			model.Id = id;
			model.Name = precastReinforce.Name;
			model.Count = precastReinforce.Count;
			model.PrecastType = precastReinforce.PrecastType;
			model.Project = precastReinforce.Project;
			model.Reinforced = precastReinforce.Reinforced;
			model.Produced = precastReinforce.Produced;
			model.Reinforce = precastReinforce.Reinforce;
			model.TotalReinforce = precastReinforce.TotalReinforce;

			return View(model);
		}

		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Production(int id, [FromQuery] AllPrecastProductionQueryModel model)
		{
			PrecastProductionQueryModel precastProduction = await precastService.GetPrecastProductionAsync(
				id,
				model.CurrentPage,
				AllPrecastProductionQueryModel.PrecastPerPage);

			model.Id = id;
			model.Name = precastProduction.Name;
			model.Count = precastProduction.Count;
			model.PrecastType = precastProduction.PrecastType;
			model.Project = precastProduction.Project;
			model.Reinforced = precastProduction.Reinforced;
			model.Produced = precastProduction.Produced;
			model.Precast = precastProduction.Precast;
			model.TotalPrecast = precastProduction.TotalPrecast;

			return View(model);

		}
	}

}

PrecastFactorySystem/Controllers/ProduceController.cs
namespace PrecastFactorySystem.Web.Controllers
{
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Mvc;

	using PrecastFactorySystem.Core.Contracts;
	using PrecastFactorySystem.Core.Exceptions;
	using PrecastFactorySystem.Core.Models;
	using PrecastFactorySystem.Core.Models.Produce;
	using PrecastFactorySystem.Infrastructure.Data.Models;
	using PrecastFactorySystem.Web.Attributes;

	using static PrecastFactorySystem.Core.Constants.MessageConstants;


	public class ProduceController : BaseController
	{
		private readonly IProduceService produceService;
		private readonly IBaseServise baseService;

		public ProduceController(
			IProduceService _productionService,
			IBaseServise _baseService)
		{
			produceService = _productionService;
			baseService = _baseService;

		}

		[Authorize(Roles = "Administrator, PrecastProductionManager")]
		[PrecastExists]
		[HttpGet]
		public async Task<IActionResult> Produce(int id)
		{
			try
			{
				ProduceFormViewModel model = await produceService.GetProductionFormAsync(id);
				return View(model);
			}
			catch (ProduceActionException pae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = pae.Message
				});
			}

		}

		[Authorize(Roles = "Administrator, PrecastProductionManager")]
		[PrecastExists]
		[HttpPost]
		public async Task<IActionResult> Produce(int id, ProduceFormViewModel model)
		{
			try
			{
				int maxCount = await produceService.GetPrecastToProduceCountAsync(id, null);

				if (model.ProducedCount > maxCount)
				{
					ModelState.AddModelError(nameof(model.ProducedCount),
						string.Format(InvalidProduceCountErrorMessage, maxCount));
				}

				if (!ModelState.IsValid)
				{
					model.Departments = await baseService.GetBaseEntityDataAsync<Department>();
					return View(model);
				}

				await produceService.ProducePrecastAsync(id, model);
				TempData["Message"] = "You have successfully added production record!";
				return RedirectToAction("Production", "Precast", new { id });
			}
			catch (ProduceActionException pae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = pae.Message
				});
			}

		}

		[Authorize(Roles = "Administrator, PrecastProductionManager")]
		[ProductionRecordExists]
		public async Task<IActionResult> Edit(int id)
		{
			ProduceFormViewModel model = await produceService.GetProductionRecordByIdAsync(id);
			return View(model);
		}

		[Authorize(Roles = "Administrator, PrecastProductionManager")]
		[ProductionRecordExists]
		[HttpPost]
		public async Task<IActionResult> Edit(int id, ProduceFormViewModel model)
		{
			try
			{
				int precastId = model.PrecastId;

				int maxCount = await produceService.GetPrecastToProduceCountAsync(precastId, id);

				if (model.ProducedCount > maxCount)
				{
					ModelState.AddModelError(nameof(model.ProducedCount),
												string.Format(InvalidProduceCountErrorMessage, maxCount));
				}

				if (!ModelState.IsValid)
				{
					model.Departments = await baseService.GetBaseEntityDataAsync<Department>
						(d => d.DepartmentType == Infrastructure.Data.Enums.DepartmentType.PrecastProduction);
					return View(model);
				}

				await produceService.EditProductionRecordAsync(id, model);
				TempData["Message"] = "You have successfully edited production record!";
				return RedirectToAction("Production", "Precast", new { id = precastId });
			}
			catch (ProduceActionException pae)
			{

				return View("BaseError", new BaseErrorViewModel()
				{
					Message = pae.Message
				});
			}

		}


		[Authorize(Roles = "Administrator, PrecastProductionManager")]
		[ProductionRecordExists]
		public async Task<IActionResult> Delete(int id, int precastId)
		{
			await produceService.DeleteProductionRecordAsync(id);

			TempData["Message"] = "You have successfully deleted production record!";
			return RedirectToAction("Production", "Precast", new { id = precastId });
		}
	}
}

PrecastFactorySystem/Views/Precast/AddReinforce.cshtml
@model ReinforceFormViewModel
@{
	ViewBag.Title = "Add reinforce to precast";
}

<h4 class="text-center">@ViewBag.Title</h4>
<hr />
<div class="container">
	<div class="row">
		<div class="col-sm-6 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6 ">
			<form asp-controller="Precast" asp-action="AddReinforce" method="post">
				<div class="bg-dark text-light">
					<label asp-for="@Model.Position" class="form-label-add-edit">Position</label>
					<input asp-for="@Model.Position" class="form-control" aria-required="true" />
					<span asp-validation-for="@Model.Position" class="text-danger"></span>
				</div>

				<div class="bg-dark text-light">
					<label asp-for="@Model.Count" class="form-label-add-edit">Count</label>
					<input asp-for="@Model.Count" class="form-control" aria-required="true" />
					<span asp-validation-for="@Model.Count" class="text-danger"></span>
				</div>
				<div class="bg-dark text-light">
					<label asp-for="@Model.ReinforceTypeId" class="form-label-add-edit">Select Reinforce Type</label>
					<select class="bg-dark text-light" asp-for="@Model.ReinforceTypeId" class="form-control" aria-required="true">
						<option disabled selected value="">Select Reinforce Type...</option>
						@foreach (var type in Model.ReinforceTypes)
						{
							<option value="@type.Id">@type.Name</option>
							@(Model.SpecificMass = type.SpecificMass);
						}
					</select>
					<span asp-validation-for="@Model.ReinforceTypeId" class="text-danger"></span>
				</div>
				<div hidden class="bg-dark text-light">
					<label asp-for="@Model.SpecificMass" class="form-label-add-edit">Length m</label>
					<input asp-for="@Model.SpecificMass" class="form-control" aria-required="true" />
					<span asp-validation-for="@Model.SpecificMass" class="text-danger"></span>
				</div>
				<div class="bg-dark text-light">
					<label asp-for="@Model.Length" class="form-label-add-edit">Length m</label>
					<input asp-for="@Model.Length" class="form-control" aria-required="true" />
					<span asp-validation-for="@Model.Length" class="text-danger"></span>
				</div>
				<div class="bg-dark text-light">
					<input class="btn btn-secondary mb-2 w-100 p-3 fw-bold" type="submit" value="Add" />
				</div>
			</form>
		</div>
	</div>
</div>
@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

PrecastFactorySystem/Views/Precast/Production.cshtml
@using System.Security.Claims
@model AllPrecastProductionQueryModel

@{
	ViewBag.Title = "Precast production by Departments";
}

<h3 class="text-center">@ViewBag.Title</h3>

<div class="d-flex p-2 justify-content-between">
	<div>
		<p disabled class="mb-0"><span class="fw-bold">Id: </span>@Model.Id</p>
		<p class="mb-0"><span class="fw-bold">Type: </span>@Model.PrecastType</p>
		<p class="mb-0"><span class="fw-bold">Precast: </span>@Model.Name</p>
		<p class="mb-0"><span class="fw-bold">Count: </span>@Model.Count</p>
	</div>
	<div>
		<p class="mb-0"><span class="fw-bold">Project: </span>@Model.Project</p>
		<p class="mb-0"><span class="fw-bold">Reinforced: </span>@Model.Reinforced</p>
		<p class="mb-0"><span class="fw-bold">Produced: </span>@Model.Produced</p>
	</div>
</div>
<div class="text-center mt-4 p-5">
	@if (User.IsAdmin() || User.IsPrecastProductionManager())
	{
		<a asp-area="" asp-controller="Produce" asp-action="Produce" asp-route-id="@Model.Id" class="btn btn-dark ">Mark as produced</a>
	}
	<a asp-area="" asp-controller="Precast" asp-action="All" class="btn btn-dark ">Back to all precast </a>
</div>

<hr />
@{
	var previousPage = Model.CurrentPage - 1;
	if (previousPage < 1)
	{
		previousPage = 1;
	}

	var maxPage = Math.Ceiling((double)Model.TotalPrecast /
		AllPrecastProductionQueryModel.PrecastPerPage);
}

<div class="row mb-5">
	<div class="col-sm-6 d-grid gap-2 d-sm-flex justify-content-sm-start">
		<a class="btn btn-secondary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
		   asp-controller="Precast"
		   asp-action="Production"
		   asp-route-id="@Model.Id"
		   asp-route-currentPage="@previousPage"><<</a>
	</div>

	@{
		var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
		!Model.Precast.Any();
	}

	<div class="col-sm-6 d-grid gap-2 d-sm-flex justify-content-sm-end">
		<a class="btn btn-secondary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
		   asp-controller="Precast"
		   asp-action="Production"
		   asp-route-id="@Model.Id"
		   asp-route-currentPage="@(Model.CurrentPage + 1)">>></a>
	</div>
</div>

<partial name="_PrecastProductionPartial" model="@Model.Precast" />

PrecastFactorySystem/Views/Precast/Reinforce.cshtml
@using System.Security.Claims
@model AllPrecastReinforceQueryModel

@{
	ViewBag.Title = "Precast reinforce";
}

<h3 class="text-center">@ViewBag.Title</h3>

<div class="d-flex p-2 justify-content-between">
	<div>
		<p disabled class="mb-0"><span class="fw-bold">Id: </span>@Model.Id</p>
		<p class="mb-0"><span class="fw-bold">Type: </span>@Model.PrecastType</p>
		<p class="mb-0"><span class="fw-bold">Precast: </span>@Model.Name</p>
		<p class="mb-0"><span class="fw-bold">Count: </span>@Model.Count</p>
	</div>
	<div>
		<p class="mb-0"><span class="fw-bold">Project: </span>@Model.Project</p>
		<p class="mb-0"><span class="fw-bold">Reinforced: </span>@Model.Reinforced</p>
		<p class="mb-0"><span class="fw-bold">Produced: </span>@Model.Produced</p>
	</div>
</div>
<div class="text-center mt-4 p-5">
	@if (User.IsAdmin() || User.IsReinforceManager())
	{
		<a asp-area="" asp-controller="Reinforce" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-dark ">Add Reinforce</a>
		<a asp-area="" asp-controller="Order" asp-action="Order" asp-route-id="@Model.Id" class="btn btn-dark ">Order</a>
		<a asp-area="" asp-controller="Order" asp-action="ForPrecast" asp-route-id="@Model.Id" class="btn btn-dark ">Precast Orders</a>
		<a asp-area="" asp-controller="Precast" asp-action="All" class="btn btn-dark ">Back to all precast </a>
	}

</div>

<hr />
@{
	var previousPage = Model.CurrentPage - 1;
	if (previousPage < 1)
	{
		previousPage = 1;
	}

	var maxPage = Math.Ceiling((double)Model.TotalReinforce /
		AllPrecastReinforceQueryModel.ReinforcePerPage);
}

<div class="row mb-5">
	<div class="col-sm-6 d-grid gap-2 d-sm-flex justify-content-sm-start">
		<a class="btn btn-secondary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
		   asp-controller="Precast"
		   asp-action="Reinforce"
		   asp-route-id="@Model.Id"
		   asp-route-currentPage="@previousPage"><<</a>
	</div>

	@{
		var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
		!Model.Reinforce.Any();
	}

	<div class="col-sm-6 d-grid gap-2 d-sm-flex justify-content-sm-end">
		<a class="btn btn-secondary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
		   asp-controller="Precast"
		   asp-action="Reinforce"
		   asp-route-id="@Model.Id"
		   asp-route-currentPage="@(Model.CurrentPage + 1)">>></a>
	</div>
</div>
<div>
	<partial name="_PrecastReinforcePartial" model=@Model.Reinforce />
</div>

PrecastFactorySystem/Views/Precast/_PrecastProductionPartial.cshtml
@using System.Security.Claims
@model IEnumerable<PrecastProductionViewModel>

<table class="table table-hover table-borderless">
	<thead>
		<tr>
			<th scope="col">Id</th>
			<th scope="col">PrecastId</th>
			<th scope="col">Department</th>
			<th scope="col">Count</th>
			<th scope="col">Date</th>
		</tr>
	</thead>
	<tbody class="table-group-divider">

		@foreach (var record in Model)
		{
			<tr>
				<td disabled>@record.Id</td>
				<td disabled>@record.PrecastId</td>
				<td>@record.Department</td>
				<td>@record.Count</td>
				<td>@record.Date</td>
				@if (User.IsAdmin() || User.IsPrecastProductionManager())
				{
					<td>
						<a asp-controller="Produce"
						   asp-action="Edit"
						   asp-route-id="@record.Id"
						   class="card-link">
							Edit
						</a>
					</td>
					<td>
						<a asp-controller="Produce"
						   asp-action="Delete"
						   asp-route-id="@record.Id"
						   asp-route-precastId="@record.PrecastId"
						   onclick="return confirm('Are you sure you want to delete this record?')"
						   class="card-link">
							Delete
						</a>
					</td>
				}
			</tr>
		}
	</tbody>
</table>